### ISSUE TITLE
Markdown not decoding properly

### ISSUE THREAD

**Issue by tyeeman** [alexanderte/simple-website#4]
Very nice! Just tried it and it works good, however some of my markdown is not being decoded properly. It would be nice to choose the markdown parser to use. 
Here is the markdown - 
```
4. Build the blog:

	```
	$ ./app build
    Generating: index.html
    Generating: tags/reference.html
    Generating: tags/tutorial.html
    Generating: tags/advanced.html
    Generating: tags/docs.html
    Generating: tags/basics.html
    Generating: overview.html
    Generating: quick-start.html
    Generating: installation.html
    Generating: creating-a-blog.html
    Generating: creating-posts.html
    Generating: generating-html-files-for-a-blog-aka-building-a-blog.html
    Generating: serving-a-blog.html
    Generating: templates.html
    Generating: getting-help.html
    ```
```
Here is what it should look like - 
```
$ ./app build
Generating: index.html
Generating: tags/reference.html
Generating: tags/tutorial.html
Generating: tags/advanced.html
Generating: tags/docs.html
Generating: tags/basics.html
Generating: overview.html
Generating: quick-start.html
Generating: installation.html
Generating: creating-a-blog.html
Generating: creating-posts.html
Generating: generating-html-files-for-a-blog-aka-building-a-blog.html
Generating: serving-a-blog.html
Generating: templates.html
Generating: getting-help.html
```
Here is what simple-website gives -
![2019-01-03_103442](https://user-images.githubusercontent.com/4469306/50654904-48cb0180-0f43-11e9-975c-a92fd23efab4.png)

So looks like code tags (```) are not decoded properly.

**Comment by alexanderte** [comment]
Are you sure you are using simple-website? The output doesn’t look familiar. simple-website currently uses v1 of russross/blackfriday by the way. Common extensions are enabled. I’m closing this issue as it seems not to be a simple-website issue.

**Comment by tyeeman** [comment]
You can ignore the content. It's just a readme file from another static generator. I updated what simple-website gives when it runs into "code" tags. You can see line feeds are not generated in code blocks. Try some markdown code blocks yourself and see if it works.

**Comment by alexanderte** [comment]
Now I understand. I’m re-opening the issue, and I’ll look into it.

**Comment by tyeeman** [comment]
Comparing your site source code to mine, looks like the <pre> tags on yours (which work) are <p> tags on mine (don't work).

**Comment by alexanderte** [comment]
Have you tried not using the ``` and indented the code using four spaces (i.e. not tabs)? That’s what I do on my website. The ``` syntax might be supported. I haven’t tried it. (And I don’t have access to simple-website/my website where I’m now, so I cannot test it right now.

**Comment by alexanderte** [comment]
I should mention that I had the blue line there because I though it looked good. One problem is that quotations often are styled in a similar manner. That’s one of the reasons why I removed it.

The latest version of simple-website might look a bit different than the one you’re using now. I hope you like it.

**Comment by alexanderte** [comment]
I’m not sure if I fully get you. But rendering as code by indenting four spaces should have worked since the initial version of simple-website. Very recently I enabled common extensions which among other things makes it possible to render tables. I still haven’t tried it out, but fenced code blocks might work.

**Comment by alexanderte** [comment]
I just tried out fenced code blocks, and that seems to work as well.

Is it okay if I close this issue?

**Comment by tyeeman** [comment]
Sure, all is good now.

**Comment by alexanderte** [comment]
That’s great!
